kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    run: bobo
  namespace: bobo
  name: bobo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: bobo
  template:
    metadata:
      labels:
        run: bobo
    spec:
      containers:
      - image: quay.io/hahappyman/alp.goweb:v2
        name: myweb
        ports:
         - containerPort: 8080
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -u -r /opt/web/* /opt/www/"]
        volumeMounts:
        - mountPath: /opt/www
          name: bobo-volume
      volumes:
      - name: bobo-volume
        persistentVolumeClaim:
          claimName: pvc-bobo
