apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bobo
  namespace: bobo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: mynfs
